### ISSUE TITLE
Error with K8s Auth Method

### ISSUE THREAD

**Issue by linuxbsdfreak** [ricoberger/vault-secrets-operator#124]
Hi  @ricoberger 

I am getting the following error in the operator

400. Errors:\n\n* 1 error occurred:\n\t* error running lookahead function for mfa: could not parse UID from claims\n\n","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:225"

I saw this https://github.com/hashicorp/vault-plugin-auth-kubernetes/issues/107

It say something related to JWT token. I am configuing it via TF.

Kevin

**Comment by ricoberger** [comment]
Mh this looks good to me. Does the same error occur, when you use the steps from the readme, instead of Terraform to configure Vault: https://github.com/ricoberger/vault-secrets-operator#kubernetes-auth-method

**Comment by linuxbsdfreak** [comment]
@ricoberger . Yes i tried the same steps in the README and get the same error. 

```
              - name: VAULT_KUBERNETES_PATH
                value: auth/kubernetes
              - name: VAULT_AUTH_METHOD
                value: kubernetes
```

**Comment by linuxbsdfreak** [comment]
K8s version is 1.21.5 and Vault Enterprise 1.7.3

**Comment by ricoberger** [comment]
I tried to reproduce the issue in the tests (#127) with your Kubernetes and Vault version without success. The only think I get is the `claim "iss" is invalid` error when not setting `disable_iss_validation=true`.

Looking at https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/108, which fixes the problem within Vault  it looks like this was not backported to Vault 1.7.x and is only available in the [Vault 1.8.x](https://github.com/hashicorp/vault/pull/12092). Maybe you can try to update your Vault version to 1.8.x?

**Comment by linuxbsdfreak** [comment]
@ricoberger Thx. I even tried disable_iss_validation=true and it still did not work. I will try to check with Vault 1.8.x

**Comment by linuxbsdfreak** [comment]
So i validated on 1.8.x and it worked if i set disable_iss_validation=true

**Comment by ricoberger** [comment]
Nice 🙂

You can also set the `issuer` instead `disable_iss_validation`, see #128.

**Comment by ira-gordin-sap** [comment]
Hi @ricoberger,
I have the same issue with K8s version is 1.21.5 and Vault Enterprise 1.7.3 and https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.5.0.
Hope you plan patch 1.7 as well.
Thanks,
Ira

**Comment by ricoberger** [comment]
Hi @ira-gordin-sap, it's not possible to fix the issue for Vault 1.7.x, because the problem is within Vault and Kubernetes 1.21.x JWT tokens. The fix was only backported to Vault 1.8.x.

**Comment by Kampe** [comment]
Seeing a similar issue with vault 1.8.4 and K8s 1.21.5 all of a sudden - the fix is just set validation to false?

**Comment by ricoberger** [comment]
@Kampe, yes this should fix the issue. Setting the validation to false or setting the issuer should work. I would prefer the second one.

To [find out the issuer](https://www.vaultproject.io/docs/auth/kubernetes#discovering-the-service-account-issuer) you can use the following commands:

```sh
kubectl proxy
curl --silent http://127.0.0.1:8001/api/v1/namespaces/default/serviceaccounts/default/token -H "Content-Type: application/json" -X POST -d '{"apiVersion": "authentication.k8s.io/v1", "kind": "TokenRequest"}' | jq -r '.status.token' | cut -d . -f2 | base64 -D
```

**Comment by Kampe** [comment]
I have just set the issuer and still receive the same error: 

```
{"level":"info","ts":1637090862.4138372,"logger":"vault","msg":"Reconciliation is enabled.","ReconciliationTime":60}
{"level":"error","ts":1637090866.0996177,"msg":"Could not create API client for Vault","error":"Error making API request.\n\nURL: PUT https://myvault.com/v1/auth/cluster/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nmain.main\n\t/workspace/main.go:56\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

<img width="336" alt="Screen Shot 2021-11-16 at 1 33 46 PM" src="https://user-images.githubusercontent.com/624150/142053225-68a1c490-5f66-449a-bc00-fc73d0420482.png">

**Comment by Kampe** [comment]
> @Kampe, yes this should fix the issue. Setting the validation to false or setting the issuer should work. I would prefer the second one.
> 
> To [find out the issuer](https://www.vaultproject.io/docs/auth/kubernetes#discovering-the-service-account-issuer) you can use the following commands:
> 
> ```shell
> kubectl proxy
> curl --silent http://127.0.0.1:8001/api/v1/namespaces/default/serviceaccounts/default/token -H "Content-Type: application/json" -X POST -d '{"apiVersion": "authentication.k8s.io/v1", "kind": "TokenRequest"}' | jq -r '.status.token' | cut -d . -f2 | base64 -D
> ```

also, using this command on GKE does not yield any results and just hangs.

**Comment by ricoberger** [comment]
Does the other command from the Vault documentation returns any results?

```sh
# In the first terminal
kubectl proxy

# In a seconde terminal
curl --silent http://127.0.0.1:8001/.well-known/openid-configuration | jq -r .issuer
```

**Comment by Kampe** [comment]
> Does the other command from the Vault documentation returns any results?
> 
> ```shell
> # In a first terminal
> kubectl proxy
> 
> # In a seconde terminal
> curl --silent http://127.0.0.1:8001/.well-known/openid-configuration | jq -r .issuer
> ```

the WK config call does work and returns a google endpoint 👍

**Comment by ricoberger** [comment]
Hi @ira-gordin-sap you have to update Vault to version 1.8.x, to fix the issue.

**Comment by ira-gordin-sap** [comment]
> Hi @ira-gordin-sap you have to update Vault to version 1.8.x, to fix the issue.

@ricoberger if I set issuer and disable_iss_validation=true, should it work in 1.7.x (just for test)?

**Comment by ricoberger** [comment]
@ira-gordin-sap if you get the following error `Errors:\n\n* 1 error occurred:\n\t* error running lookahead function for mfa: could not parse UID from claims\n\n","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:225"` I think setting the issuer or disable_iss_validation will not work.

If you see the following error `Error making API request.\n\nURL: PUT https://myvault.com/v1/auth/cluster/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid` it might be enough to set the issuer or disable_iss_validation, but I didn't tested it.

**Comment by ira-gordin-sap** [comment]
@ricoberger I have
`error running lookahead function for mfa: could not parse UID from claims`
So nothing can help but Vault version 1.8.x

**Comment by linuxbsdfreak** [comment]
@ira-gordin-sap @ricoberger 

I tested it once more today with Vault 1.8.4 and K8s 1.22.1. 

```
vault write auth/csi/config token_reviewer_jwt=$SA_JWT_TOKEN_CSI kubernetes_host=$K8S_HOST kubernetes_ca_cert=$SA_CA_CRT_CSI issuer=$ISSUE disable_iss_validation="true"
```

I even tried this which works for Vault 1.8.4 and K8s 1.22.1

https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver?in=vault/kubernetes

For Vault version 1.7.4 i get 

```
PUT https://myvault.com/v1/auth/cluster/login\nCode: 500. Errors:\n\n* claim \"iss\" is invalid
```

**Comment by ricoberger** [comment]
With Vault 1.9.0 the issue will not be validated anymore, so that it should be save to set `disable_iss_validation`, see https://www.vaultproject.io/docs/auth/kubernetes#kubernetes-1-21

For that I would close the issue now, if someone still have problems with Kubernetes 1.21 and above and the Vault 1.9.0 please let me know.
